// <auto-generated />
using CRUD_PeriferiaIT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_PeriferiaIT.Migrations
{
    [DbContext(typeof(VuelosContext))]
    [Migration("20211018001824_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD_PeriferiaIT.Models.Vuelos", b =>
                {
                    b.Property<int>("VueloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aerolinia")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CiudadDestino")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CiudadOrigen")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EstadoVuelo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fecha")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoraLlegada")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoraSalida")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroVuelo")
                        .HasColumnType("int");

                    b.HasKey("VueloID");

                    b.ToTable("Vuelos");
                });
#pragma warning restore 612, 618
        }
    }
}
